# SROS2 Keystore and Policy Configuration for Smart Wheelchair / TurtleBot3

keystore_name: "wheelchair_keystore"   #wheelchair_keystore

# By default, use the official standard path for ROS 2 security: ~/.ros/sros2/keystore
# Can be overridden with an absolute path if a custom directory is desired.
keystore_path: "~/.ros/sros2/wheelchair_keystore"

# Active policy type:
# - "wheelchair" (Unified enclave '/wheelchair' mapping all navigation/control nodes to one identity)
# - "wheelchair_individual" (Separate enclaves for '/livox_driver', '/dlio_odom_node', '/wheelchair2_base_controller', '/navigation')
# - "turtlebot3" (Enclaves for TurtleBot3 simulation and nodes, including cmd_vel_publisher, cmd_vel_subscriber, fake_cmd_vel_publisher, gazebo, turtlebot3, etc.)
policy_type: "wheelchair"

# Enclaves definitions mapping policy XML files
policies:
  wheelchair:
    policy_file: "wheelchair_policy.xml"
    enclaves:
      - name: "/"
      - name: "/wheelchair"
  
  wheelchair_individual:
    policy_file: "wheelchair_individual_policy.xml"
    enclaves:
      - name: "/"
      - name: "/livox_driver"
      - name: "/dlio_odom_node"
      - name: "/wheelchair2_base_controller"
      - name: "/navigation"


  turtlebot3:
    policy_file: "turtlebot3_policy.xml"
    enclaves:
      - name: "/"
      - name: "/cmd_vel_publisher"
      - name: "/cmd_vel_subscriber"
      - name: "/fake_cmd_vel_publisher"
      - name: "/gazebo"
      - name: "/gazebo_ros_factory"
      - name: "/gazebo_ros_force_system"
      - name: "/turtlebot3_diff_drive"
      - name: "/turtlebot3_imu"
      - name: "/turtlebot3_joint_state"
      - name: "/camera_driver"
      - name: "/robot_state_publisher"
      - name: "/spawn_entity"
      - name: "/turtlebot3"
